# Generated by Django 3.0.1 on 2019-12-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tag_text', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField()),
                ('layer', models.IntegerField(default=-1)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
